Header header           # timestamp in the header is the time the
                        # interace node received the range event
string source_address   #
string anchor_address   #
string tag_address      #
int32 range_dist_mm     # distance in mm
int32 range_rsl_mm      # distance in mm
int32 range_raw_mm      # distance in mm
float32 rsl_db          # received signal level in decibels
